### ISSUE TITLE
Your web app is ready! 🚀

### ISSUE THREAD

**Issue by sleepingexperiments** [ananyakumar9/flutter_ecommerce_app#1]
Hey! 👋

Someone has requested a demo of your project using [Ukoreh](https://ukoreh.fun/)! 🧙‍♂️.

The app compiled fine and is now live at https://flutter-preview.github.io/ananyakumar9-flutter_ecommerce_app

**Comment by ananyakumar9** [comment]
Thank you!
App still under development.
